yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"
urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_posts"),
    path("create/", views.post_create, name="post_create"),
    path("follow/", views.follow_index, name="follow_index"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("posts/<int:post_id>/comment/", views.add_comment,
         name="add_comment"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("profile/<str:username>/follow/", views.profile_follow,
         name="profile_follow"),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = "core.views.page_not_found"
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path("about/", include("about.urls", namespace="about")),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("posts.urls", namespace="posts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

yatube/posts/models.py
from core.models import CreatedModel
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """Модель сообществ в которые
    можно публиковать статьи"""

    title = models.CharField("Название группы", max_length=200)
    slug = models.SlugField("Адрес группы", unique=True)
    description = models.TextField("Описание группы")

    class Meta:
        verbose_name_plural = "Группы"

    def __str__(self):
        """Значение выводимое при печати"""
        return f"{self.title}"


class Post(CreatedModel):
    """Модель статьи в блоге."""

    text = models.TextField("Текст поста", help_text="Введите текст поста")
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="posts",
        verbose_name="Группа",
        help_text="Группа, к которой будет относиться пост",
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="posts",
        verbose_name="Автор"
    )
    image = models.ImageField("Картинка", upload_to="posts/", blank=True)

    def __str__(self):
        """Значение выводимое при печати"""
        return f"{self.text[:15]}"

    class Meta:
        ordering = ("-created",)
        verbose_name_plural = "Статьи"


class Comment(CreatedModel):
    """Описывает модель комментариев."""

    post = models.ForeignKey(
        Post, verbose_name="Пост", related_name="comments",
        on_delete=models.CASCADE
    )

    author = models.ForeignKey(
        User, verbose_name="Автор", related_name="comments",
        on_delete=models.CASCADE
    )
    text = models.TextField(
        verbose_name="Текст комментария"
    )

    class Meta:
        ordering = ("-created",)
        verbose_name = "комментарий"
        verbose_name_plural = "комментарии"

    def __str__(self):
        """Определяет отображение комментария
        при преобразовании его в строку."""
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
        verbose_name="Подписчик",
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="following",
        verbose_name="Автор"
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "author"], name="follow_unique")
        ]

    def __str__(self):
        return f"{self.author}, follower:{self.user}"

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["text"].widget.attrs[
            "placeholder"
        ] = "Введите какой нибудь текст, ну пожалуйста 😥"
        self.fields["group"].empty_label = "Выберите группу🙂"

    class Meta:
        model = Post
        labels = {"group": "Группа", "text": "Текст поста"}
        help_texts = {"group": "Выберите группу", "text": "Введите ссообщение"}
        fields = ("text", "group", "image")


class CommentForm(ModelForm):
    """Создаёт форму по модели поста."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["text"].widget.attrs[
            "placeholder"
        ] = "Введите какой нибудь текст комментария"

    class Meta:
        model = Comment
        fields = ("text",)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import paginator_page


@cache_page(20, key_prefix="index_page")
def index(request):
    page_obj = paginator_page(request, Post.objects.select_related("author"))
    context = {
        "title": "Последние обновления на сайте",
        "page_obj": page_obj,
    }
    return render(request, "posts/index.html", context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    page_obj = paginator_page(request, group.posts.select_related("group"))
    context = {"group": group, "page_obj": page_obj}
    return render(request, "posts/group_list.html", context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    page_obj = paginator_page(request, author.posts.select_related("author"))
    following = (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user, author=author).exists()
    )
    context = {"author": author, "page_obj": page_obj, "following": following}
    return render(request, "posts/profile.html", context)


def post_detail(request, post_id):
    post = get_object_or_404(Post.objects.select_related("author"), id=post_id)
    comments = post.comments.all().select_related("author")
    context = {
        "post": post,
        "form": CommentForm(),
        "comments": comments,
    }
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request):
    context = {
        "title": "Новый пост",
    }
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return redirect("posts:profile", request.user)
    context["form"] = form
    return render(request, "posts/create_post.html", context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect("posts:post_detail", post_id)
    context = {"title": "Редактировать запись", "post": post, "is_edit": True}
    form = PostForm(request.POST or None, files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post.id)
    context["form"] = form
    return render(request, "posts/create_post.html", context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        form.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.select_related("author").filter(
        author__following__user=request.user
    )
    page_obj = paginator_page(request, post_list)
    template = "posts/follow.html"
    context = {
        "title": "Посты в подписке",
        "page_obj": page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect("posts:profile", author)


@login_required
def profile_unfollow(request, username):
    Follow.objects.filter(
        user=request.user, author__username=username).delete()
    return redirect("posts:profile", username)

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/form_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
      {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/form_validate.html
{% load user_filters %}
<div class="form-group row my-3 p-3">
  <label for="{{ field.id_for_label }}">
    {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
  </label>
  {{ field|addclass:"form-control" }}
  {% if field.help_text %}
    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
      {{ field.help_text }}
    </small>
  {% endif %}
</div>

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    {% with request.resolver_match.view_name as view_name %}
    <ul class="nav nav-pills">
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Об
          авторе</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
          href="{% url 'about:tech' %}">Технологии</a>
      </li>
      {% if user.is_authenticated  %}
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
          href="{% url 'posts:post_create' %}">Новая запись</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'users:password_change_form' %}active{% endif %}"
          href="{% url 'users:password_change_form' %}">Изменить пароль</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}"
          href="{% url 'users:logout' %}">Выйти</a>
      </li>
      <li class="nav-item navbar-text">
        Пользователь:
        <a href="{%url 'posts:profile' user.username %}">
          {{ user.username }}
        </a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}"
          href="{% url 'users:login' %}">Войти</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}"
          href="{% url 'users:signup' %}">Регистрация</a>
      </li>
      {% endif %}
      {% endwith %}
    </ul>
  </div>
</nav>

yatube/templates/includes/post.html
{% load thumbnail %}
<article>
  <ul>
    <li>Автор: <a href="{%url 'posts:profile' post.author.username %}">
        {{ post.author.get_full_name }}
      </a>
    </li>
    <li>Дата публикации: {{ post.created|date:"d E Y" }}</li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text|linebreaks }}</p>
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
  <br>
  {% if post.group and page == 'index_page' %}
    все записи группы <a href="{% url 'posts:group_posts' post.group.slug %}"> {{ post.group.title }} </a>
  {% endif %}
</article>