yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"
urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_posts"),
    path("create/", views.post_create, name="post_create"),
    path("follow/", views.follow_index, name="follow_index"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("posts/<int:post_id>/comment/", views.add_comment,
         name="add_comment"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("profile/<str:username>/follow/", views.profile_follow,
         name="profile_follow"),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = "core.views.page_not_found"
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path("about/", include("about.urls", namespace="about")),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("posts.urls", namespace="posts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

yatube/posts/models.py
from core.models import CreatedModel
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """Модель сообществ в которые
    можно публиковать статьи"""

    title = models.CharField("Название группы", max_length=200)
    slug = models.SlugField("Адрес группы", unique=True)
    description = models.TextField("Описание группы")

    class Meta:
        verbose_name_plural = "Группы"

    def __str__(self):
        """Значение выводимое при печати"""
        return f"{self.title}"


class Post(CreatedModel):
    """Модель статьи в блоге."""

    text = models.TextField("Текст поста", help_text="Введите текст поста")
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="posts",
        verbose_name="Группа",
        help_text="Группа, к которой будет относиться пост",
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="posts",
        verbose_name="Автор"
    )
    image = models.ImageField("Картинка", upload_to="posts/", blank=True)

    def __str__(self):
        """Значение выводимое при печати"""
        return f"{self.text[:15]}"

    class Meta:
        ordering = ("-created",)
        verbose_name_plural = "Статьи"


class Comment(CreatedModel):
    """Описывает модель комментариев."""

    post = models.ForeignKey(
        Post, verbose_name="Пост", related_name="comments",
        on_delete=models.CASCADE
    )

    author = models.ForeignKey(
        User, verbose_name="Автор", related_name="comments",
        on_delete=models.CASCADE
    )
    text = models.TextField(
        verbose_name="Текст комментария"
    )

    class Meta:
        ordering = ("-created",)
        verbose_name = "комментарий"
        verbose_name_plural = "комментарии"

    def __str__(self):
        """Определяет отображение комментария
        при преобразовании его в строку."""
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
        verbose_name="Подписчик",
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="following",
        verbose_name="Автор"
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "author"], name="follow_unique")
        ]

    def __str__(self):
        return f"{self.author}, follower:{self.user}"

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["text"].widget.attrs[
            "placeholder"
        ] = "Введите какой нибудь текст, ну пожалуйста 😥"
        self.fields["group"].empty_label = "Выберите группу🙂"

    class Meta:
        model = Post
        labels = {"group": "Группа", "text": "Текст поста"}
        help_texts = {"group": "Выберите группу", "text": "Введите ссообщение"}
        fields = ("text", "group", "image")


class CommentForm(ModelForm):
    """Создаёт форму по модели поста."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["text"].widget.attrs[
            "placeholder"
        ] = "Введите какой нибудь текст комментария"

    class Meta:
        model = Comment
        fields = ("text",)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import paginator_page


@cache_page(20, key_prefix="index_page")
def index(request):
    page_obj = paginator_page(request, Post.objects.select_related("author"))
    context = {
        "title": "Последние обновления на сайте",
        "page_obj": page_obj,
    }
    return render(request, "posts/index.html", context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    page_obj = paginator_page(request, group.posts.select_related("group"))
    context = {"group": group, "page_obj": page_obj}
    return render(request, "posts/group_list.html", context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    page_obj = paginator_page(request, author.posts.select_related("author"))
    following = (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user, author=author).exists()
    )
    context = {"author": author, "page_obj": page_obj, "following": following}
    return render(request, "posts/profile.html", context)


def post_detail(request, post_id):
    post = get_object_or_404(Post.objects.select_related("author"), id=post_id)
    comments = post.comments.all().select_related("author")
    context = {
        "post": post,
        "form": CommentForm(),
        "comments": comments,
    }
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request):
    context = {
        "title": "Новый пост",
    }
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return redirect("posts:profile", request.user)
    context["form"] = form
    return render(request, "posts/create_post.html", context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect("posts:post_detail", post_id)
    context = {"title": "Редактировать запись", "post": post, "is_edit": True}
    form = PostForm(request.POST or None, files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post.id)
    context["form"] = form
    return render(request, "posts/create_post.html", context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        form.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.select_related("author").filter(
        author__following__user=request.user
    )
    page_obj = paginator_page(request, post_list)
    template = "posts/follow.html"
    context = {
        "title": "Посты в подписке",
        "page_obj": page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect("posts:profile", author)


@login_required
def profile_unfollow(request, username):
    Follow.objects.filter(
        user=request.user, author__username=username).delete()
    return redirect("posts:profile", username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock title %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать пост
            {% else %}
              Новый пост
            {% endif %}
          </div>
          <div class="card-body">
            {% include 'includes/form_errors.html' %}
            <form method="post" enctype="multipart/form-data" {% if action_url %} action="{% url action_url %}" {% endif %}>
            {% csrf_token %}
            {% for field in form %}
              {% include 'includes/form_validate.html' %}
            {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
           </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1> {{title}} </h1>
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'includes/post.html' with page='index_page' %}
        {% if not forloop.last %}
          <hr>
        {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  {{ group.title }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description|linebreaks }}</p>
    {% for post in page_obj %}
      {% include 'includes/post.html' with page='group_page' %}
        {% if not forloop.last %}
          <hr>
        {% endif %}
      {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1> {{title}} </h1>
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'includes/post.html' with page='index_page' %}
        {% if not forloop.last %}
          <hr>
        {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load user_filters %}
{% load thumbnail %}
{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.created|date:"d E Y" }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
            Группа: {{ group.title }}
            <a href="{%url 'posts:group_posts' post.group.slug %}">
            все записи группы
            </a>
            </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора: <span> {{ post.author.posts.count }} </span>
          </li>
          <li class="list-group-item">
            <a href="{%url 'posts:profile' post.author.username %}">
            все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        {% if post.author == request.user %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            Редактировать пост
          </a>
        {% endif %}
        
        {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
              <div class="card-body">
                <form method="post" action="{% url 'posts:add_comment' post.id %}">
                  {% csrf_token %}      
                  <div class="form-group mb-2">
                    {{ form.text|addclass:"form-control" }}
                  </div>
                  <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
              </div>
          </div>
        {% endif %}

        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
              <p>
                {{ comment.text }}
              </p>
            </div>
          </div>
        {% endfor %} 
      </article>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Профайл пользователя {{author.username}}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="mb-5">        
      <h1>Все посты пользователя {{ author.first_name }} {{ author.last_name }}</h1>
      <h3>Всего постов: {{ author.posts.count }}</h3>
      {% if user.is_authenticated and user.username != author.username  %}
        {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
        Отписаться
        </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
          Подписаться
          </a>
        {% endif %}
      {% endif %}
    </div>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Дата публикации: {{ post.created|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text|linebreaksbr}}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">
          Подробная информация
        </a>
      </article> 
      {% if post.group %}
        Все записи группы <a href="{% url 'posts:group_posts' post.group.slug %}"> {{ post.group }} </a>
      {% endif %}        
      {% if not forloop.last %} 
        <hr>
      {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}